# syntax=docker/dockerfile:1

FROM golang:1.18

ARG GOPROXY=https://goproxy.cn,direct

WORKDIR /app

COPY main.go  .
COPY go.sum .
COPY go.mod .

RUN go mod download

RUN go build -o /docker-go-demo



EXPOSE 3000

CMD [ "/docker-go-demo" ]
