# syntax=docker/dockerfile:1

# Build

FROM golang:1.18-buster AS build
ARG GOPROXY=https://goproxy.cn,direct
WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go ./

RUN go build -o /docker-go-demo

## Deploy

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /docker-go-demo /docker-go-demo

EXPOSE 3000

USER nonroot:nonroot

CMD ["/docker-go-demo"]
