# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

ARG GOPROXY=https://goproxy.cn,direct

WORKDIR /app

COPY go.sum .

COPY go.mod .

RUN go mod download

COPY *.go  .

RUN go build -o /docker-go-demo

EXPOSE 3000

CMD [ "/docker-go-demo" ]
